// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfeFMXOE30CQGJJRTN1ePz3QqyfMHG70I',
    appId: '1:314135528220:web:007d7402180dd632c430d9',
    messagingSenderId: '314135528220',
    projectId: 'mus-building',
    authDomain: 'mus-building.firebaseapp.com',
    storageBucket: 'mus-building.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTHdGMMqOy4FOilyiJupvljLmuUAsgYzU',
    appId: '1:314135528220:android:a1061984040af35bc430d9',
    messagingSenderId: '314135528220',
    projectId: 'mus-building',
    storageBucket: 'mus-building.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfeFMXOE30CQGJJRTN1ePz3QqyfMHG70I',
    appId: '1:314135528220:web:cddc8203232a23cbc430d9',
    messagingSenderId: '314135528220',
    projectId: 'mus-building',
    authDomain: 'mus-building.firebaseapp.com',
    storageBucket: 'mus-building.appspot.com',
  );
}
